CREATE TABLE FORUM_SUBCATEGORIES (
ID NUMBER,
CONSTRAINT FORUM_SUBCATEGORY_PK PRIMARY KEY (ID),
ID_CATEGORY NUMBER,
CONSTRAINT ID_CATEGORY_FK FOREIGN KEY (ID_CATEGORY) REFERENCES FORUM_CATEGORIES(ID),
TITLE NVARCHAR2(64),
DESCRIPTION CLOB,
DAT_E TIMESTAMP,
IP NVARCHAR2(20)
);
